CREATE TABLE [dbo].[Credentials]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[UserId] INT NOT NULL,
	[CredentialTypeId] INT NOT NULL,
	[Identifier] NVARCHAR(50) NOT NULL,
	[Secret] NVARCHAR(50) NOT NULL,
	CONSTRAINT FK_UserCredential FOREIGN KEY (UserId)
	REFERENCES Users(Id)
)